<table class="table">
    <tr>
        <th>Book</th>
        <th>Compatibility</th>
        <th>Book Date</th>
        <th>Female AVG age</th>
        <th>Male AVG age</th>
    </tr>
    <?php foreach ($this->books as $book) : ?>
        <tr>
            <td><?= $this->escapeHtml($book->name) ?></td>
            <td><?= $book->compatibility ?>%</td>
            <td><?= $book->bookDate ?></td>
            <td><?= number_format($book->femaleAVG, 2, '.', ''); ?></td>
            <td><?= number_format($book->maleAVG, 2, '.', ''); ?></td>
        </tr>
    <?php endforeach; ?>
</table>