name: Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing PHP Setup
    steps:
      - name: Disable the GitHub API proxy
        run: sudo sed -i '/api.github.com/d' /etc/hosts
      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "8.2"
